### ISSUE TITLE
Suggestion: Use render props to render children 

### ISSUE THREAD

**Issue by FiberJW** [Hehk/reason-react-context#2]
I couldn't get Consumer to work with a function as a child because ReasonReact types all children as arrays. changing it to a render prop fixes it:

```ocaml
module type Config = {type state; let name: string; let defaultValue: state;};

module CreateContext = (C: Config) => {
  type action =
    | ChangeState(C.state);
  let state = ref(C.defaultValue);
  let subscriptions = ref([]);
  let addSubscription = f => {
    subscriptions := [f, ...subscriptions^];
    () => subscriptions := List.filter(sub => sub !== f, subscriptions^);
  };
  let updateState = newStateOpt => {
    let newState =
      switch (newStateOpt) {
      | None => C.defaultValue
      | Some(newValue) => newValue
      };
    state := newState;
    List.iter(f => f(newState), subscriptions^);
  };
  module Provider = {
    let component =
      ReasonReact.statelessComponent(C.name ++ "ContextProvider");
    let make = (~value=?, ~render, _children) => {
      ...component,
      willReceiveProps: _self => updateState(value),
      didMount: _self => {
        updateState(value);
        ReasonReact.NoUpdate;
      },
      render: _self => render(),
    };
  };
  module Consumer = {
    let component = ReasonReact.reducerComponent(C.name ++ "ContextConsumer");
    let make = (~render, children) => {
      ...component,
      initialState: () => state^,
      reducer: (action, _state) =>
        switch (action) {
        | ChangeState(newState) => ReasonReact.Update(newState)
        },
      subscriptions: ({send}) => [
        Sub(
          () => addSubscription(newState => send(ChangeState(newState))),
          unSub => unSub(),
        ),
      ],
      render: ({state}) => render(state),
    };
  };
};
```

**Comment by fiber-god** [comment]
Here's the working code in the app: https://github.com/fiber-god/pico/commit/480671926edab7b02e0d4850707b1a640ed30485

**Comment by fiber-god** [comment]
and here's the article i referenced to learn about reason render props https://jaredforsyth.com/posts/advanced-reasonreact-hider-order-components/

**Comment by Hehk** [comment]
Sorry for not responding X.x I lost this in all the github messages from work.

I do think having the render function in a prop makes the code look a bit better. Currently I am trying to keep this library an implementation of the normal React context api which uses a render prop on the children prop.

**Comment by guilhermedecampo** [comment]
we are using @FiberJW version and it's pretty great with render props!
@FiberJW would be cool if you maintain a repo with that.

**Comment by FiberJW** [comment]
@guilhermedecampo say no more 👌🏿

**Comment by guilhermedecampo** [comment]
Looking forward please send the link!

**Comment by FiberJW** [comment]
@guilhermedecampo Do you use the `<Provider>` much at all? I know it's there to emulate the upstream React Context API, but it seems that from how it's implemented in Reason that it truly isn't necessary

**Comment by guilhermedecampo** [comment]
Yes, I do use! 
Let's discuss this in another issue? Maybe in your new repository?
Don't wanna bother @Hehk! 

I can share with you how I've been using. 
And maybe you have better alternatives!

**Comment by FiberJW** [comment]
@guilhermedecampo here: https://github.com/FiberJW/stature/issues/1
